version: '3'
services:
  dex:
    image: ghcr.io/dexidp/dex:v2.37.0
    volumes:
      - ${PWD}/dex/config.docker.yaml:/etc/dex/config.docker.yaml
    ports:
      - 5556:5556


#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
